### ISSUE TITLE
M::I doesn't read utf8-encoded files correctly

### ISSUE THREAD

**Issue by sjn** [Perl-Toolchain-Gang/Module-Install#37]
Module/Install.pm's _read() and _write() functions don't set the encoding correctly, leading to utf8-bugs in the author field in META.yml. Here's how to reproduce this error:

Create two files; `Makefile.PL`...

```
use inc::Module::Install;
all_from 'lib/Broken.pm';

requires();
auto_install();
&WriteAll;
```

...and `lib/Broken.pm`

```
package Broken;

use 5.006;
our $VERSION = '1.0';

1;

__END__

=encoding utf8

=head1 NAME

Broken - A broken module

=head1 DESCRIPTION

This module is only here to show a bug

=head1 AUTHORS

Philippe "BooK" Bruhat, Éric Cholet, Olivier Mengué

=head1 LICENSE

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.

=cut
```

Make sure the AUTHORS field is saved correctly as utf8. You can check this with `xxd -g1 -s 179 -l 70  lib/Broken.pm`, which should give the following output:

```
00000b3: 3d 68 65 61 64 31 20 41 55 54 48 4f 52 53 0a 0a  =head1 AUTHORS..
00000c3: 50 68 69 6c 69 70 70 65 20 22 42 6f 6f 4b 22 20  Philippe "BooK" 
00000d3: 42 72 75 68 61 74 2c 20 c3 89 72 69 63 20 43 68  Bruhat, ..ric Ch
00000e3: 6f 6c 65 74 2c 20 4f 6c 69 76 69 65 72 20 4d 65  olet, Olivier Me
00000f3: 6e 67 75 c3 a9 0a                                ngu...
```

Then, run `perl Makefile.PL`, using Module::Install version 1.12. The following META.yml will then be generated:

```

---
abstract: 'A broken module'
author:
  - "Philippe \"BooK\" Bruhat, �\x89ric Cholet, Olivier Mengué"
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.12'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Broken
name: Broken
no_index:
  directory:
    - inc
requires:
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: '1.0'
```

The error is in the author field, specifically `�\x89ric Cholet`.

The following patch to Module::Install with fix the issue:

```
--- lib/Module/Install.pm.orig  2014-10-20 15:35:13.731849265 +0200
+++ lib/Module/Install.pm   2014-10-20 15:36:52.326525499 +0200
@@ -18,6 +18,8 @@

 use 5.006;
 use strict 'vars';
+use utf8;
+use open ':encoding(utf8)';
 use Cwd        ();
 use File::Find ();
 use File::Path ();
```

This parch will make one test in the Module::Install's test suite fail. Not sure what's going on there.
